[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "openpyxl>=3.1.5",
    "plotly>=6.0.1",
    "sqlalchemy>=2.0.40",
    "streamlit>=1.44.1",
    "xlsxwriter>=3.2.3",
]
